spring.application.name=Day23

#management.endpoints.web.exposure.include=health,metrics,beans,info,mappings
#management.endpoint.health.show-details=always
#management.info.env.enabled=true

#spring.security.user.name=admin
#spring.security.user.password=admin123

spring.profiles.active=prod

server.port=8084
